name: flutter_lottie
description: Use lottie in flutter to render animations for iOS and Android
version: 0.2.1
author: Harry Le <harryle.fit@gmail.com>
homepage: https://github.com/harrylefit/flutter_lottie

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_lottie
        pluginClass: FlutterLottiePlugin
      ios:
        pluginClass: FlutterLottiePlugin
